### ISSUE TITLE
Question about the example code in the book

### ISSUE THREAD

**Issue by yodalee** [gergoerdi/retroclash-book-code#1]
I recently bought the book of retroclash.
I found that the code of HelloRegister cannot compile. The HelloRegister in ch 4:
```haskell
import Clash.Prelude
import Clash.Annotations.TH

helloRegister :: Clock System -> Reset System -> Enable System -> Signal System Bool
helloRegister clk rst en = register clk rst en True (pure False)
```
When I load the program in `clashi`, it gives me the type error on `rst`:
```txt
blink.hs:11:41: error:
    • Couldn't match expected type: Signal dom0 (Clock System)
                  with actual type: Reset System
    • In the second argument of ‘register’, namely ‘rst’
      In the expression: register clk rst en True (pure False)
      In an equation for ‘helloRegister’:
          helloRegister clk rst en = register clk rst en True (pure False)
   |
11 | helloRegister clk rst en = register clk rst en True (pure False)
   |                                         ^^^
```

Do you have any hints about how to fix this?

**Comment by gergoerdi** [comment]
The very first handful of examples use `Clash.Explicit.Prelude` instead of `Clash.Prelude`  to show how exactly the clock, reset, and enable signals are propagated to every `register` (and why it'd be tedious to do that for larger circuits). The full example in the book that you're quoting looks like this (from page 44):

```
import Clash.Explicit.Prelude

helloRegister 
    :: Clock System -> Reset System -> Enable System 
    -> Signal System Bool
helloRegister clk rst en = register clk rst en True (pure False)
```

Later code in the book, from page 51 onward, we do indeed use the Clash API with implicit clock routing (i.e. `Clash.Prelude` instead of `Clash.Explicit.Prelude`). These introductory examples are meant to show "walking before running".

**Comment by yodalee** [comment]
Yes I think it works now. Thank for your response.
